load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "platform",
    srcs = [
        "performance_analyzer.py",
    ],
    deps = [
        "//core/common_runtime:common_runtime",
        "//core/util:util",
    ],
    visibility = ["//visibility:public"],
)

