import torch
import torch.nn as nn

class Ad(nn.Module):
    """
    Transformer architecture generated by TruthGPT Model Architect.
    Specs: 11 layers, 5 heads, 333 dim, DeepNorm norm.
    """
    def __init__(self, vocab_size=50257):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, 333)
        self.layers = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=333, 
                nhead=5, 
                batch_first=True,
                norm_first=True if "DeepNorm" == "RMSNorm" else False
            ) for _ in range(11)
        ])
        self.head = nn.Linear(333, vocab_size)
        
    def forward(self, x):
        x = self.embedding(x)
        for layer in self.layers:
            x = layer(x)
        return self.head(x)

# Model injected into TruthGPT SOTA Registry
def get_model():
    return Ad()
