"""
Lazy Import Definitions for Optimization Core

This module organizes all lazy import mappings by category for better
maintainability and discoverability.
"""

from typing import Dict

# Main lazy imports - core optimization components
_LAZY_IMPORTS: Dict[str, str] = {
    # CUDA and Triton kernels - moved to modules.acceleration.gpu
    'OptimizedLayerNorm': '.modules.acceleration.gpu.cuda_kernels',
    'OptimizedRMSNorm': '.modules.acceleration.gpu.cuda_kernels',
    'CUDAOptimizations': '.modules.acceleration.gpu.cuda_kernels',
    'TritonLayerNorm': '.modules.optimizers.techniques.triton_optimizations',
    'TritonOptimizations': '.modules.optimizers.techniques.triton_optimizations',
    
    # Training components
    'EnhancedGRPOTrainer': '.utils.enhanced_grpo',
    'EnhancedGRPOArgs': '.utils.enhanced_grpo',
    'KalmanFilter': '.utils.enhanced_grpo',
    'MCTSOptimizer': '.modules.optimizers.mcts.mcts_optimization',
    'MCTSOptimizationArgs': '.modules.optimizers.mcts.mcts_optimization',
    'create_mcts_optimizer': '.modules.optimizers.mcts.mcts_optimization',
    'EnhancedPPOActor': '.utils.parallel_training',
    'ParallelTrainingConfig': '.utils.parallel_training',
    'create_parallel_actor': '.utils.parallel_training',
    'ReplayBuffer': '.utils.experience_buffer',
    'Experience': '.utils.experience_buffer',
    'PrioritizedExperienceReplay': '.utils.experience_buffer',
    'create_experience_buffer': '.utils.experience_buffer',
    
    # Losses and rewards
    'GRPOLoss': '.utils.advanced_losses',
    'EnhancedGRPOLoss': '.utils.advanced_losses',
    'AdversarialLoss': '.utils.advanced_losses',
    'CurriculumLoss': '.utils.advanced_losses',
    'create_loss_function': '.utils.advanced_losses',
    'GRPORewardFunction': '.utils.reward_functions',
    'AdaptiveRewardFunction': '.utils.reward_functions',
    'MultiObjectiveRewardFunction': '.utils.reward_functions',
    'create_reward_function': '.utils.reward_functions',
    
    # Normalization and embeddings
    'AdvancedRMSNorm': '.modules.optimizers.techniques.advanced_normalization',
    'LlamaRMSNorm': '.modules.optimizers.techniques.advanced_normalization',
    'CRMSNorm': '.modules.optimizers.techniques.advanced_normalization',
    'AdvancedNormalizationOptimizations': '.modules.optimizers.techniques.advanced_normalization',
    'create_advanced_rms_norm': '.modules.optimizers.techniques.advanced_normalization',
    'create_llama_rms_norm': '.modules.optimizers.techniques.advanced_normalization',
    'create_crms_norm': '.modules.optimizers.techniques.advanced_normalization',
    'RotaryEmbedding': '.optimizers.techniques.positional_encodings',
    'LlamaRotaryEmbedding': '.optimizers.techniques.positional_encodings',
    'FixedLlamaRotaryEmbedding': '.optimizers.techniques.positional_encodings',
    'AliBi': '.optimizers.techniques.positional_encodings',
    'SinusoidalPositionalEmbedding': '.optimizers.techniques.positional_encodings',
    'PositionalEncodingOptimizations': '.optimizers.techniques.positional_encodings',
    'create_rotary_embedding': '.optimizers.techniques.positional_encodings',
    'create_llama_rotary_embedding': '.optimizers.techniques.positional_encodings',
    'create_alibi': '.optimizers.techniques.positional_encodings',
    'create_sinusoidal_embedding': '.optimizers.techniques.positional_encodings',
    
    # MLP components
    'SwiGLU': '.optimizers.techniques.enhanced_mlp',
    'GatedMLP': '.optimizers.techniques.enhanced_mlp',
    'MixtureOfExperts': '.optimizers.techniques.enhanced_mlp',
    'AdaptiveMLP': '.optimizers.techniques.enhanced_mlp',
    'EnhancedMLPOptimizations': '.optimizers.techniques.enhanced_mlp',
    'create_swiglu': '.optimizers.techniques.enhanced_mlp',
    'create_gated_mlp': '.optimizers.techniques.enhanced_mlp',
    'create_mixture_of_experts': '.optimizers.techniques.enhanced_mlp',
    'create_adaptive_mlp': '.optimizers.techniques.enhanced_mlp',
    
    # Kernel fusion and quantization
    'FusedLayerNormLinear': '.modules.acceleration.gpu.kernel_fusion',
    'FusedAttentionMLP': '.modules.acceleration.gpu.kernel_fusion',
    'KernelFusionOptimizer': '.modules.acceleration.gpu.kernel_fusion',
    'create_kernel_fusion_optimizer': '.modules.acceleration.gpu.kernel_fusion',
    'QuantizedLinear': '.advanced_quantization',
    'QuantizedLayerNorm': '.advanced_quantization',
    'AdvancedQuantizationOptimizer': '.advanced_quantization',
    'create_quantization_optimizer': '.advanced_quantization',
    
    # Models
    'ModelManager': '.modules.models',
    'ModelBuilder': '.modules.models',
    'HFTransformersModel': '.modules.models',
    'create_hf_transformers_model': '.modules.models',
    'HFDiffusersModel': '.modules.models',
    'create_hf_diffusers_model': '.modules.models',
    'DiffusionManager': '.modules.models',
    'AttentionUtils': '.modules.models',
    'create_model': '.modules.models',
    'MODEL_REGISTRY': '.modules.models',
    
    # Memory pooling - moved to utils.memory
    'TensorPool': '.utils.memory.memory_pooling',
    'ActivationCache': '.utils.memory.memory_pooling',
    'MemoryPoolingOptimizer': '.utils.memory.memory_pooling',
    'create_memory_pooling_optimizer': '.utils.memory.memory_pooling',
    'get_global_tensor_pool': '.utils.memory.memory_pooling',
    'get_global_activation_cache': '.utils.memory.memory_pooling',
    
    # Enhanced CUDA - moved to modules.acceleration.gpu
    'AdvancedCUDAConfig': '.modules.acceleration.gpu.enhanced_kernels',
    'FusedKernelOptimizer': '.modules.acceleration.gpu.enhanced_kernels',
    'MemoryCoalescingOptimizer': '.modules.acceleration.gpu.enhanced_kernels',
    'QuantizationKernelOptimizer': '.modules.acceleration.gpu.enhanced_kernels',
    'EnhancedCUDAOptimizations': '.modules.acceleration.gpu.enhanced_kernels',
    'create_enhanced_cuda_optimizer': '.modules.acceleration.gpu.enhanced_kernels',
    
    # Learning strategies - moved to modules/learning module
    'ActiveLearner': '.modules.learning.active',
    'AdaptiveLearner': '.modules.learning.adaptive_learning',
    'AdversarialLearner': '.modules.learning.adversarial',
    'EnsembleLearner': '.modules.learning.ensemble_learning',
    'TransferLearner': '.modules.learning.transfer_learning',
    'ContinualLearner': '.modules.learning.continual_learning',
    'SelfSupervisedLearner': '.modules.learning.self_supervised_learning',
    'FederatedLearner': '.modules.learning.federated_learning',
    'MetaLearner': '.modules.learning.meta',
    'MultitaskLearner': '.modules.learning.multitask_learning',
    'ReinforcementLearner': '.modules.learning.reinforcement',
    'BayesianOptimizer': '.modules.learning.bayesian_optimization',
    'HyperparameterOptimizer': '.modules.learning.hyperparameter_optimization',
    'EvolutionaryOptimizer': '.modules.learning.evolutionary',
    'CausalInferenceSystem': '.modules.learning.causal',
    'CausalInferenceEngine': '.modules.learning.causal',
    'CausalInference': '.modules.learning.causal',
    
    # Optimization cores - consolidated imports
    # Optimization cores - consolidated imports
    'UltraOptimizationCore': '.modules.optimizers.optimization_cores',
    'create_ultra_optimization_core': '.modules.optimizers.optimization_cores',
    'SuperOptimizationCore': '.modules.optimizers.optimization_cores',
    'create_super_optimization_core': '.modules.optimizers.optimization_cores',
    'MetaOptimizationCore': '.modules.optimizers.optimization_cores',
    'create_meta_optimization_core': '.modules.optimizers.optimization_cores',
    'HyperOptimizationCore': '.modules.optimizers.optimization_cores',
    'create_hyper_optimization_core': '.modules.optimizers.optimization_cores',
    'QuantumOptimizationCore': '.modules.optimizers.optimization_cores',
    'create_quantum_optimization_core': '.modules.optimizers.optimization_cores',
    'NextGenOptimizationEngine': '.modules.optimizers.advanced.next_gen_engine',
    'HyperSpeedOptimizer': '.modules.optimizers.advanced.hyper_speed',
    'UltraAIOptimizer': '.modules.optimizers.advanced.ultra_ai',
    'SyntheticMultiverseOptimizationSystem': '.modules.optimizers.advanced.multiverse_system',
    'NeuralEvolutionaryOptimizer': '.modules.optimizers.advanced.evolutionary',
    'NASOptimizationCore': '.modules.advanced.neural_architecture_search',
    'create_nas_optimization_core': '.modules.advanced.neural_architecture_search',
    # Optimization cores - now organized in optimizers.optimization_cores
    'EnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_enhanced_optimization_core': '.optimizers.optimization_cores',
    'UltraEnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_ultra_enhanced_optimization_core': '.optimizers.optimization_cores',
    'MegaEnhancedOptimizationCore': '.optimizers.optimization_cores',
    'create_mega_enhanced_optimization_core': '.optimizers.optimization_cores',
    'SupremeOptimizationCore': '.optimizers.optimization_cores',
    'create_supreme_optimization_core': '.optimizers.optimization_cores',
    'TranscendentOptimizationCore': '.optimizers.optimization_cores',
    'create_transcendent_optimization_core': '.optimizers.optimization_cores',
    'HybridOptimizationCore': '.optimizers.optimization_cores',
    'create_hybrid_optimization_core': '.optimizers.optimization_cores',
    'UltraFastOptimizationCore': '.optimizers.optimization_cores',
    'create_ultra_fast_optimization_core': '.optimizers.optimization_cores',
    # Unified factory
    'create_optimization_core': '.optimizers.optimization_cores',
    'OPTIMIZATION_CORE_REGISTRY': '.optimizers.optimization_cores',
    'list_available_cores': '.optimizers.optimization_cores',
    'get_core_info': '.optimizers.optimization_cores',
    
    # RL and pruning
    'RLPruning': '.modules.optimizers.techniques.rl_pruning',
    'RLPruningAgent': '.modules.optimizers.techniques.rl_pruning',
    'RLPruningOptimizations': '.modules.optimizers.techniques.rl_pruning',
    'create_rl_pruning': '.modules.optimizers.techniques.rl_pruning',
    'create_rl_pruning_agent': '.modules.optimizers.techniques.rl_pruning',
    
    # Advanced registry
    'AdvancedOptimizationConfig': '.advanced_optimization_registry_v2',
    'get_advanced_optimization_config': '.advanced_optimization_registry_v2',
    'apply_advanced_optimizations': '.advanced_optimization_registry_v2',
    'get_advanced_optimization_report': '.advanced_optimization_registry_v2',
    
    # MCTS and benchmarks - now organized in optimizers.specialized
    'EnhancedMCTSWithBenchmarks': '.modules.optimizers.specialized',
    'EnhancedMCTSBenchmarkArgs': '.modules.optimizers.specialized',
    'create_enhanced_mcts_with_benchmarks': '.modules.optimizers.specialized',
    'benchmark_mcts_comparison': '.modules.optimizers.specialized',
    'MCTSOptimizer': '.modules.optimizers.specialized',
    'MCTSOptimizationArgs': '.modules.optimizers.specialized',
    'create_mcts_optimizer': '.modules.optimizers.specialized',
    # Specialized optimizers
    'EnhancedParameterOptimizer': '.modules.optimizers.specialized',
    'EnhancedParameterConfig': '.modules.optimizers.specialized',
    'create_enhanced_parameter_optimizer': '.modules.optimizers.specialized',
    'optimize_model_parameters': '.modules.optimizers.specialized',
    'LibraryOptimizer': '.modules.optimizers.specialized',
    'AIExtremeOptimizer': '.modules.optimizers.specialized',
    'ExtremeSpeedOptimizationSystem': '.modules.optimizers.specialized',
    'PyTorchInspiredOptimizer': '.modules.optimizers.specialized',
    'create_specialized_optimizer': '.modules.optimizers.specialized',
    'SPECIALIZED_OPTIMIZER_REGISTRY': '.modules.optimizers.specialized',
    'list_available_specialized_optimizers': '.modules.optimizers.specialized',
    'get_specialized_optimizer_info': '.modules.optimizers.specialized',
    # TruthGPT-specific optimizers - now organized in optimizers.truthgpt
    'TruthGPTDynamoOptimizer': '.modules.optimizers.truthgpt',
    'TruthGPTDynamoLevel': '.modules.optimizers.truthgpt',
    'TruthGPTDynamoResult': '.modules.optimizers.truthgpt',
    'create_truthgpt_dynamo_optimizer': '.modules.optimizers.truthgpt',
    'TruthGPTInductorOptimizer': '.modules.optimizers.truthgpt',
    'TruthGPTInductorLevel': '.modules.optimizers.truthgpt',
    'TruthGPTInductorResult': '.modules.optimizers.truthgpt',
    'create_truthgpt_inductor_optimizer': '.modules.optimizers.truthgpt',
    'TruthGPTQuantizationOptimizer': '.modules.optimizers.truthgpt',
    'TruthGPTQuantizationLevel': '.modules.optimizers.truthgpt',
    'TruthGPTQuantizationResult': '.modules.optimizers.truthgpt',
    'create_truthgpt_quantization_optimizer': '.modules.optimizers.truthgpt',
    'SupremeTruthGPTOptimizer': '.modules.optimizers.truthgpt',
    'SupremeOptimizationLevel': '.modules.optimizers.truthgpt',
    'SupremeOptimizationResult': '.modules.optimizers.truthgpt',
    'TransformerOptimizer': '.modules.optimizers.truthgpt',
    'create_truthgpt_optimizer_by_type': '.modules.optimizers.truthgpt',
    'TRUTHGPT_OPTIMIZER_REGISTRY': '.modules.optimizers.truthgpt',
    'list_available_truthgpt_optimizers': '.modules.optimizers.truthgpt',
    'get_truthgpt_optimizer_info': '.modules.optimizers.truthgpt',
    # Core optimizers - now organized in core.optimizers
    'ExtremeOptimizer': '.core.optimizers',
    'ExtremeOptimizationLevel': '.core.optimizers',
    'ExtremeOptimizationResult': '.core.optimizers',
    'QuantumNeuralOptimizer': '.core.optimizers',
    'CosmicOptimizer': '.core.optimizers',
    'TranscendentOptimizer': '.core.optimizers',
    'QuantumOptimizer': '.core.optimizers',
    'UltraFastOptimizer': '.core.optimizers',
    'ParallelOptimizer': '.core.optimizers',
    'CacheOptimizer': '.core.optimizers',
    'EnhancedOptimizer': '.core.optimizers',
    'EnhancedOptimizationLevel': '.core.optimizers',
    'EnhancedOptimizationResult': '.core.optimizers',
    'ComplementaryOptimizer': '.core.optimizers',
    'ComplementaryOptimizationLevel': '.core.optimizers',
    'ComplementaryOptimizationResult': '.core.optimizers',
    'AdvancedComplementaryOptimizer': '.core.optimizers',
    'MicroservicesOptimizer': '.core.optimizers',
    'OptimizerService': '.core.optimizers',
    'QuantumInspiredOptimizer': '.core.optimizers',
    'MetaLearningOptimizer': '.core.optimizers',
    'create_core_optimizer': '.core.optimizers',
    'CORE_OPTIMIZER_REGISTRY': '.core.optimizers',
    'list_available_core_optimizers': '.core.optimizers',
    'get_core_optimizer_info': '.core.optimizers',
    # Registries - now organized in registries module
    'ServiceRegistry': '.registries',
    'ServiceContainer': '.registries',
    'register_service': '.registries',
    'get_service': '.registries',
    'DatasetRegistry': '.registries',
    'register_dataset': '.registries',
    'build_dataset': '.registries',
    'AdvancedOptimizationConfig': '.registries',
    'get_advanced_optimizations': '.registries',
    'apply_advanced_optimizations': '.registries',
    'get_advanced_optimization_report': '.registries',
    'AdvancedOptimizationConfigV2': '.registries',
    'get_advanced_optimization_config_v2': '.registries',
    'apply_advanced_optimizations_v2': '.registries',
    'get_advanced_optimization_report_v2': '.registries',
    'CommitTrackerOptimizationRegistry': '.registries',
    'get_registry': '.registries',
    'REGISTRY_REGISTRY': '.registries',
    'list_available_registries': '.registries',
    'get_registry_info': '.registries',
    'OlympiadBenchmarkSuite': '.olympiad_benchmarks',
    'OlympiadBenchmarkConfig': '.olympiad_benchmarks',
    'OlympiadProblem': '.olympiad_benchmarks',
    'ProblemCategory': '.olympiad_benchmarks',
    'DifficultyLevel': '.olympiad_benchmarks',
    'get_olympiad_benchmark_config': '.olympiad_benchmarks',
    'create_olympiad_benchmark_suite': '.olympiad_benchmarks',
    
    # Optimization profiles
    'OptimizationProfile': '.optimization_profiles',
    'get_optimization_profiles': '.optimization_profiles',
    'apply_optimization_profile': '.optimization_profiles',
    
    # Parameter optimization
    'EnhancedParameterOptimizer': '.enhanced_parameter_optimizer',
    'EnhancedParameterConfig': '.enhanced_parameter_optimizer',
    'create_enhanced_parameter_optimizer': '.enhanced_parameter_optimizer',
    'optimize_model_parameters': '.enhanced_parameter_optimizer',
    'calculate_parameter_efficiency': '.parameter_optimization_utils',
    'optimize_learning_rate_schedule': '.parameter_optimization_utils',
    'optimize_rl_parameters': '.parameter_optimization_utils',
    'optimize_temperature_parameters': '.parameter_optimization_utils',
    'optimize_quantization_parameters': '.parameter_optimization_utils',
    'optimize_memory_parameters': '.parameter_optimization_utils',
    'generate_model_specific_optimizations': '.parameter_optimization_utils',
    'benchmark_parameter_optimization': '.parameter_optimization_utils',
}

# Core modules lazy imports
_CORE_LAZY_IMPORTS: Dict[str, str] = {
    'BaseOptimizer': '.core.common_runtime',
    'OptimizationStrategy': '.core.common_runtime',
    'OptimizationResult': '.core.common_runtime',
    'OptimizationLevel': '.core.common_runtime',
    'OptimizationConfig': '.core.common_runtime',
    'Environment': '.core.common_runtime',
    'ConfigManager': '.core.common_runtime',
    'SystemMonitor': '.core.common_runtime',
    'ModelValidator': '.core.common_runtime',
    'CacheManager': '.core.common_runtime',
    'PerformanceUtils': '.core.common_runtime',
    'MemoryUtils': '.core.common_runtime',
    'GPUUtils': '.modules.acceleration.gpu.gpu_utils',
}

# Compiler lazy imports
_COMPILER_LAZY_IMPORTS: Dict[str, str] = {
    'CompilerCore': '.compiler',
    'CompilationTarget': '.compiler',
    'CompilationResult': '.compiler',
    'create_compiler_core': '.compiler',
    'compilation_context': '.compiler',
    'AOTCompiler': '.compiler',
    'AOTCompilationConfig': '.compiler',
    'AOTOptimizationStrategy': '.compiler',
    'create_aot_compiler': '.compiler',
    'aot_compilation_context': '.compiler',
    'JITCompiler': '.compiler',
    'JITCompilationConfig': '.compiler',
    'JITOptimizationStrategy': '.compiler',
    'create_jit_compiler': '.compiler',
    'jit_compilation_context': '.compiler',
    'MLIRCompiler': '.compiler',
    'MLIRDialect': '.compiler',
    'MLIROptimizationPass': '.compiler',
    'MLIRCompilationResult': '.compiler',
    'create_mlir_compiler': '.compiler',
    'mlir_compilation_context': '.compiler',
    'CompilerPlugin': '.compiler',
    'PluginManager': '.compiler',
    'PluginRegistry': '.compiler',
    'PluginInterface': '.compiler',
    'create_plugin_manager': '.compiler',
    'plugin_compilation_context': '.compiler',
    'TF2TensorRTCompiler': '.compiler',
    'TensorRTConfig': '.compiler',
    'TensorRTOptimizationLevel': '.compiler',
    'create_tf2tensorrt_compiler': '.compiler',
    'tf2tensorrt_compilation_context': '.compiler',
    'TF2XLACompiler': '.compiler',
    'XLAConfig': '.compiler',
    'XLAOptimizationLevel': '.compiler',
    'create_tf2xla_compiler': '.compiler',
    'tf2xla_compilation_context': '.compiler',
    'CompilerUtils': '.compiler',
    'CodeGenerator': '.compiler',
    'OptimizationAnalyzer': '.compiler',
    'create_compiler_utils': '.compiler',
    'compiler_utils_context': '.compiler',
    'RuntimeCompiler': '.compiler',
    'RuntimeCompilationConfig': '.compiler',
    'RuntimeOptimizationStrategy': '.compiler',
    'create_runtime_compiler': '.compiler',
    'runtime_compilation_context': '.compiler',
    'KernelCompiler': '.compiler',
    'KernelOptimizationLevel': '.compiler',
    'KernelCompilationResult': '.compiler',
    'create_kernel_compiler': '.compiler',
    'kernel_compilation_context': '.compiler',
}

# Enterprise modules lazy imports
_ENTERPRISE_LAZY_IMPORTS: Dict[str, str] = {
    'ModuleManager': '.modules.module_manager',
    'ModuleInfo': '.modules.module_manager',
    'ModuleStatus': '.modules.module_manager',
    'get_module_manager': '.modules.module_manager',
    'EnterpriseTruthGPTAdapter': '.adapters.enterprise_truthgpt_adapter',
    'AdapterConfig': '.modules.enterprise.config',
    'AdapterMode': '.modules.enterprise.config',
    'create_enterprise_adapter': '.adapters.enterprise_truthgpt_adapter',
    'EnterpriseCache': '.modules.enterprise.cache',
    'CacheEntry': '.modules.enterprise.cache',
    'CacheStrategy': '.modules.enterprise.cache',
    'get_cache': '.modules.enterprise.cache',
    'EnterpriseAuth': '.modules.enterprise.auth',
    'User': '.modules.enterprise.auth',
    'Role': '.modules.enterprise.auth',
    'AuthMethod': '.modules.enterprise.auth',
    'Permission': '.modules.enterprise.auth',
    'get_auth': '.modules.enterprise.auth',
    'PerformanceMonitor': '.modules.enterprise.monitor',
    'Metric': '.modules.enterprise.metrics',
    'Alert': '.modules.enterprise.monitor',
    'MetricType': '.modules.enterprise.metrics',
    'AlertLevel': '.modules.enterprise.monitor',
    'get_monitor': '.modules.enterprise.monitor',
}

# Combine all lazy imports
_ALL_LAZY_IMPORTS: Dict[str, str] = {
    **_LAZY_IMPORTS,
    **_CORE_LAZY_IMPORTS,
    **_COMPILER_LAZY_IMPORTS,
    **_ENTERPRISE_LAZY_IMPORTS,
}

__all__ = [
    '_LAZY_IMPORTS',
    '_CORE_LAZY_IMPORTS',
    '_COMPILER_LAZY_IMPORTS',
    '_ENTERPRISE_LAZY_IMPORTS',
    '_ALL_LAZY_IMPORTS',
]


