load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "framework",
    srcs = [
        "ai_extreme_optimizer.py",
    ],
    deps = [
        "//core/common_runtime:common_runtime",
        "//core/platform:platform",
        "//core/util:util",
    ],
    visibility = ["//visibility:public"],
)

