"""
Configuration Constants for AI Optimization
"""

DEFAULT_LEARNING_RATE = 0.001
DEFAULT_EXPLORATION_RATE = 0.1
DEFAULT_MEMORY_DECAY = 0.95
DEFAULT_ADAPTATION_RATE = 0.1
DEFAULT_TARGET_FEATURE_SIZE = 1024
DEFAULT_EXPERIENCE_BUFFER_SIZE = 10000
DEFAULT_LEARNING_HISTORY_SIZE = 1000
DEFAULT_OPTIMIZATION_HISTORY_SIZE = 10000
DEFAULT_AI_CONFIDENCE = 0.95
MILLISECONDS_PER_SECOND = 1000
DEFAULT_DEPTH_NORMALIZATION = 100.0
DEFAULT_BATCH_SIZE_FOR_LEARNING = 100
DEFAULT_SUCCESS_THRESHOLD = 0.1
DEFAULT_SUCCESS_RATE_THRESHOLD = 0.8
DEFAULT_EXPLORATION_RATE_MIN = 0.01
DEFAULT_EXPLORATION_RATE_MAX = 0.5
DEFAULT_EXPLORATION_ADJUSTMENT = 0.95
DEFAULT_EXPLORATION_INCREASE = 1.05
DEFAULT_ACCURACY_PRESERVATION_HIGH = 0.99
DEFAULT_ACCURACY_PRESERVATION_LOW = 0.95
DEFAULT_MEMORY_REDUCTION_THRESHOLD = 0.5
DEFAULT_DROPOUT_RATE = 0.2
DEFAULT_PRUNING_AMOUNT = 0.2

DEFAULT_SPEED_IMPROVEMENT_BASE = 100.0
DEFAULT_SPEED_IMPROVEMENT_INTELLIGENT = 100.0
DEFAULT_SPEED_IMPROVEMENT_GENIUS = 1000.0
DEFAULT_SPEED_IMPROVEMENT_SUPERINTELLIGENT = 10000.0
DEFAULT_SPEED_IMPROVEMENT_TRANSHUMAN = 100000.0
DEFAULT_SPEED_IMPROVEMENT_POSTHUMAN = 1000000.0

DEFAULT_INTELLIGENCE_SCORE_NORMALIZATION = 100000.0
DEFAULT_NEURAL_ADAPTATION_MULTIPLIER = 2.0
DEFAULT_COGNITIVE_ENHANCEMENT_MULTIPLIER = 0.8
DEFAULT_METRIC_MAX_VALUE = 1.0
DEFAULT_METRIC_DIVISOR = 2.0

REQUIRED_STATE_KEYS = ('neural_network_state', 'optimizer_state', 'optimization_level')

DEFAULT_STRATEGY_CONFIDENCE = 0.5


